name: Dependabot Automerge

on:
  pull_request_target:
    branches: [main]

jobs:
  automerge:
    name: Dependabot Automerge CI
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checking out source code
        uses: actions/checkout@v3

      - name: Using Node 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test

      - name: Automerge
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.AUTO_MERGE_TOKEN }}
