name: Dependabot Continuous Integration

on:
  pull_request_target:
    branches: [main]

jobs:
  ci:
    name: CI Dependabot
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checking out source code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Using Node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Installing dependencies
        run: yarn install

      - name: Linting
        run: yarn lint

      - name: Unit Testing
        run: yarn test

      - name: Automerge
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.AUTO_MERGE_TOKEN }}
