name: Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  ci:
    name: CI
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checking out source code
        uses: actions/checkout@v3

      - name: Using Node 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Coverage
        run: yarn coverage
